// todo-list-app/src/components/NavBar.vue
<template>
  <nav class="navbar p-2 bg-dark text-white justify-content-lg-between justify-content-sm-start mb-1 ">
    <img class="navbar-brand" width="80" :src="logo" alt="Logo">
    <div class="d-flex mx-4">
      <router-link :class="linksClass" to="/">Home</router-link>
      <router-link :class="linksClass" to="/tasks-list">Tasks List</router-link>
      <router-link :class='linksClass' to="/create-new-task">CreateNewTask</router-link>
    </div>
  </nav>
</template>

<script>
export default {
  name: "NavBar",
  data(){
    return{
      linksClass:'nav-link mx-3 ',
      logo:require('../assets/images/todo logo.png')
    }
  }
}
</script>

<style scoped>
.router-link-exact-active{
  color: #4263c1;
}
.navbar-brand{
  border-radius: 70%;
}
@media(max-width: 1024px) {
}
</style>

// todo-list-react/src/components/navBar.jsx
import {NavLink, Link } from "react-router-dom";

const NavBar = ()=>{
    return (<>
    <nav className="navbar px-2 d-flex justify-content-start border-bottom border-secondary border-opacity-50 ">
        <div className="me-3">
            <p className="navbar-brand">Todo App</p>
        </div>
        <div className="flex-row d-flex justify-content-between ms-2">
            <NavLink style={({isActive})=>{
                return{
                    color:isActive ? '#1565c0' : 'black'
                }
            }} className="nav-link mx-3" to="/home">Home</NavLink>
            <NavLink style={({isActive})=>{
                return{
                    color:isActive ? '#1565c0' : 'black'
                }
            }} className="nav-link mx-3" to="/tasks">Tasks List</NavLink>
            <NavLink style={({isActive})=>{
                return{
                    color:isActive ? '#1565c0' : 'black'
                }
            }} className="nav-link mx-3" to="/create-task">Create New Task</NavLink>
        </div>
    </nav>


    </>)
}

export default NavBar;
